# Generated by Django 4.2.15 on 2025-01-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="defaults/user.png",
                upload_to="users/profile_pictures/",
                verbose_name="profile picture",
            ),
        ),
    ]
