# Generated by Django 4.2.15 on 2025-01-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
